package dev.ayagmar.quarkusforge.ui;

enum CommandPaletteAction {
  FOCUS_EXTENSION_SEARCH,
  FOCUS_EXTENSION_LIST,
  TOGGLE_FAVORITES_FILTER,
  TOGGLE_SELECTED_FILTER,
  CYCLE_PRESET_FILTER,
  JUMP_TO_FAVORITE,
  CYCLE_CATEGORY_FILTER,
  TOGGLE_CATEGORY,
  OPEN_ALL_CATEGORIES,
  RELOAD_CATALOG,
  TOGGLE_ERROR_DETAILS
}
